### ISSUE TITLE
RGB

### ISSUE THREAD

**Issue by ShumiCat** [Mezque/MicDotRecolour#2]
THIS MADE MY VRCHAT GAY

**Comment by Mezque** [comment]
true :trollface: @ShumiCat :trollface: @ShumiCat :trollface: @ShumiCat :trollface: @ShumiCat :trollface: @ShumiCat :trollface: @ShumiCat :trollface: @ShumiCat :trollface: @ShumiCat :trollface: @ShumiCat :trollface: @ShumiCat :trollface: @ShumiCat :trollface: @ShumiCat :trollface: @ShumiCat :trollface: @ShumiCat :trollface: @ShumiCat :trollface: @ShumiCat :trollface: @ShumiCat :trollface: @ShumiCat :trollface: @ShumiCat :trollface: @ShumiCat :trollface: @ShumiCat :trollface: @ShumiCat :trollface: @ShumiCat :trollface: @ShumiCat :trollface: @ShumiCat :trollface: @ShumiCat :trollface: @ShumiCat :trollface: @ShumiCat :trollface: @ShumiCat :trollface: @ShumiCat
